networks:
  mailserver-networks:
    driver: bridge
services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail.buntin.xyz
    env_file: /opt/app_config/docker/docker-mailserver/mailserver.env
    ports:
      - "25:25"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
    volumes:
      - /opt/app_config/docker/docker-mailserver/docker-data/dms/mail-data/:/var/mail/
      - /opt/app_config/docker/docker-mailserver/docker-data/dms/mail-state/:/var/mail-state/
      - /opt/app_config/docker/docker-mailserver/docker-data/dms/mail-logs/:/var/log/mail/
      - /opt/app_config/docker/docker-mailserver/docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always
    stop_grace_period: 1m
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
    networks:
      - mailserver-networks
